# Setup
title:               "AST 900: Numerical Relativity"
tagline:             'Numerical Relativity, Spring 2019'
description:         'Michigan State University - Physics and Astronomy 900: Numerical Relativity. An advanced graduate-level course covering the numerical simulation of astrophysical systems by solving Einstein's equations of general relativity.'
url:               https://msunumrel.github.io
github:
  repository_name:   https://github.com/MSUNumRel

# About/contact
author:
  name:              Sean Couch
  url:               http://pa.msu.edu/~couch
  email:             couch@pa.msu.edu

theme: jekyll-theme-cayman
